### PR TITLE
Handle italic faces

### LINKED ISSUE #18: Feature req: Italics style support
Not all terminals support italics, but the one I use does! I think it could make some intuitive styles for refined text.

### PR DESCRIPTION
**Pull request by mookid**
Fix #18 

TODO
- [x] --help should mention the new flag value

@rpdelaney  could you please test?

### CODE REVIEW

**Comment by rpdelaney** [comment]
I installed by cloning the repo, then `cargo uninstall diffr && cargo install --path .`. Version is now `diffr 0.1.3`.

First reaction: I don't see mention of italics in `--help`

**Comment by mookid** [comment]
Hi, are you sure you pulled the right branch?

it looks like that here:

```
[...]
            color_spec = face-name + ':' + attributes
            attributes = attribute
                       | attribute + ':' + attributes
            attribute  = ('foreground' | 'background') + ':' + color
                       | (<empty> | 'no') + font-flag
                       | 'none'
            font-flag  = 'italic'
                       | 'bold'
[...]
```

on git bash:
image

**Comment by rpdelaney** [comment]
Ah no, I was building from master. I will try again

**Comment by rpdelaney** [comment]
Looking good. My git config:
```sh
  diffr="diffr \                                                    
        --colors removed:background:00:foreground:01 \              
        --colors refine-removed:background:0:foreground:124:italic \
        --colors added:background:0:foreground:10 \                 
        --colors refine-added:background:0:foreground:35:intense \  
        | less -R"                                                  
                                                                    
  git config --global pager.diff "$diffr"                           
  git config --global pager.show "$diffr"                           
  git config --global pager.log "$diffr"                            
  git config --global interactive.diffFilter "$diffr"               
```

In kitty, it looks like [this](https://imgur.com/vFKU2WV), which is what I expected. 👍

**Comment by rpdelaney** [comment]
Should I wait for a new release before I expect this feature to be available from `cargo` or the AUR?

**Comment by mookid** [comment]
Hello @rpdelaney,
It will be there on the next release indeed. In the meantime, you can keep using the version from master (which should be stable anyway).

**Pull request merged**
